language: java
deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: XeYPA1H6rMope6K35lQ1PjpDivZCXrzCp2L/UzOOWzj/RQZAEdEpMPNbQ7ihWGmGEJhddgcesCCRqaoGdaCBBFZl8NP93VpoDXqQj2HfzUL4YEn0lNROGA09hFHXvC5A2AuROJ9ZWCLjKbpLFd87kv8hOV0UO3k3Y4Sg8Eoa7QnVcCto+Zyzdri0PIegwhDNzCZetoURf+HJdfaCUwrDe4ZGEv0EYItCLTp3GQNOM3dqjmMlOG+deMuZ34vA4y9k03I3A3mMjKGK97kVLocxd51OKfiA3iHKdLBFxA8nJlKB5n2rE1XB5AVWq9kaSh6Xv40U13ZcJYCXDdfMJW/549oxixGgfK9AFv3ys7hRVZABmKK80+NLnVQnLQpVTdi+au6lC/gJ6wn8k94XqnvjWZ02OyaPrLRmnZfM76W3c3G3HMRAem2D5Bbrv/nBRk5VoVJKbCvttx87LrBEg1XHxXNMheb2Lzlgj5ouFUkW6j+BD3CTRHBU/H/zfY5NLpJFaQw7LWDBuNcehmc5ympjiN5zCcFd5TAV2SqY4CYo4Qikr5/jiAWJPgiLfVeou7T+AZYafhME9AAFCubAF5k/rDlccEeV9qVYQPZ1SiIuJ6bB1QuB/xYn2Dh70ifqfgYjv7vdjbVghwKtQdZDfjVgvaF/wdmGokQS7KyRVeo/Ang=
  app: glitchless-java
  on:
    repo: java-park-mail-ru/Glitchless-09-2017
    branch: dev
