sudo: required
group: deprecated-2017Q2

services:
  - docker

addons:
  ssh_known_hosts: 54.36.181.198

cache:
  directories:
    - /home/travis/.m2

script:
  - docker build -t rhythm_blast/backend .
  - docker run
        --name db
        -d 
        -e POSTGRES_USER=backend -e POSTGRES_PASSWORD=qwerty -e POSTGRES_DB=glitchlessdb
        postgres
  - docker run 
        -e DATABASE_USER=backend -e DATABASE_PASSWORD=qwerty -e DATABASE_URL=jdbc:postgresql://db/glitchlessdb
        $(bash <(curl -s https://codecov.io/env))
        -v /home/travis/.m2:/root/.m2 
        --link db 
        rhythm_blast/backend 
        bash -c 'mvn cobertura:cobertura -B -q && bash <(curl -s https://codecov.io/bash)'

deploy:
  - provider: script
    script:
      - docker login http://registry.glitchless.ru:5000
      - docker push rhythm_blast/backend
      - ssh ansible@54.36.181.198 "cd ansible && ansible-playbook playbook.yml"
    on:
      branch: dev

before_install:
  - openssl aes-256-cbc -K $encrypted_e9c1276c6ee9_key -iv $encrypted_e9c1276c6ee9_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
